config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end
  resources :posts do
    resources :comments#,  only: [:create, :index, :new]
  end

  resources :comments

  resources "contacts", only: [:new, :create]

  get 'home/index'

  get "text/:text" => Dragonfly.app.endpoint { |params, app|
    app.generate(:text, params[:text], 'font-size' => 42)
  }

  get "image" => Dragonfly.app.endpoint { |params, app|
    app.fetch_file("some/dir/#{params[:file]}").thumb(params[:size])
  }

  root 'home#index'

end

app/models/comment.rb
# A comment is a text entry about a post
class Comment < ActiveRecord::Base
# No longer needed for Rails 4 b/c of strong parameters gem but keeping for reference
#  attr_accessible :approved,
#                  :author,
#                  :author_email,
#                  :author_url,
#                  :content,
#                  :referrer,
#                  :user_agent,
#                  :user_ip
#                  :post_id
  validates :content, presence: true
  validates :author_email, presence: true
  validates :author, presence: true
  belongs_to :commentable, polymorphic: true
end

app/controllers/comments_controller.rb
# Comments are short messages about blog posts
class CommentsController < ApplicationController
  before_filter :load_commentable, except: [:index]
  # before_action :set_comment, only: [:show, :edit]
  before_action :check_comment, only: [:show, :edit, :update, :destroy]

  def index
    authorize Comment
    @comments = Comment.all
    # @commentable = Post.find(params[:post_id])
    # @comments = @commentable.comments
  end

  def create
    # @comment = Comment.new(comment_params)
    # @post = @comment.post
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment is awaiting moderation"
      # redirect_to @post
      redirect_to @commentable
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def show
  end

  def edit
  end

  def update
    # if @post.update(post_params)
    if @the_comment.update_attributes(comment_params)
      flash[:notice] = 'Comment was successfully updated.'
      if @the_comment.class == Comment
        redirect_to comments_path
      else
        redirect_to @commentable
      end
    else
      instance_variable_set("@#{@resource.singularize}".to_sym, @commentable)
      render template: "#{@resource}/show"
    end
  end

  def destroy
    @the_comment.destroy

    redirect_to posts_url
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:author,
                                     :author_url,
                                     :author_email,
                                     :content,
                                     :referrer,
                                     :approved,
                                     :commentable_id)
    end

    def load_commentable
      @resource, id = request.path.split('/')[1,2]
      @commentable = @resource.singularize.classify.constantize.find(id)
    end

    def check_comment
      if @commentable.class == Comment
        @the_comment = @commentable
      else
        @the_comment = @commentable.comment
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  # def form_for_editor(condition, &block)
  #   if condition
  #       form_for [:editor, @commentable], :html => {class: "form"}, &block
  #   else
  #       form_for [@commentable, @comment], html: { class: 'form' }, &block
  #   end
  # end
end

app/views/comments/_comment.html.erb
<% if comment.approved? %>
<div class="comment">
  <p><u><%= comment.author %></u> commented:</p>
  <p><%= comment.content %></p>
</div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment_form">
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%#= form_for [@the_comment] do |f| %>
  <%= form_for [@commentable, @comment] do |f| %>
  <%#= form_for_editor [condition, &block] do |f| %>
    <%#= f.fields_for :comments do |pf| %>
    <div class="field">
      <%= f.label :author, "Your name" %>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :author_email, "Your email" %>
      <%= f.text_field :author_email %>
    </div>
    <div class="field">
      <%= f.label :author_url, "Your URL" %>
      <%= f.text_field :author_url %>
    </div>
    <div class="field">
      <%= f.label :content, "Your Comment" %>
      <%= f.text_field :content %>
    </div>
    <%= f.hidden_field :referrer, value: request.referrer %>
    <%= f.hidden_field :commentable_id,  value: @commentable.id %>
    <div class="actions">
      <%= f.submit "Submit comment for approval" %>
    <div>
    <%# end %>
  <% end %>
</div><!-- .comment_form -->

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

<%#= link_to 'Back', comments_path %>
<%= link_to "Cancel", :back %>

app/views/comments/index.html.erb
<h2>Admin Comments</h2>

<% @comments.each do |comment| %>
  <div <%= raw 'class="warning"' unless comment.approved? %> id="<%= dom_id(comment) %>">
    <p>Author: <%= comment.author %></p>
    <p>URL: <%= comment.author_url %></p>
    <p>Email: <%= comment.author_email %></p>
    <p>Referrer: <%= comment.referrer %></p>
    <p>Comment: <%= comment.content %></p>
    <p><%#= link_to 'Edit', [:edit, @commentable, @comment] %><%= link_to 'Edit', edit_comment_path(comment) %>
    <% if comment.approved? %>Approved
    <% else %>
      <%= button_to 'Approve', comment_path(comment, comment: { approved: true }), method: :put %>
    <% end %>
    <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %><br>----------------------------------------</p>
  </div>
  <div class="comment_content"></div>
  <div class="nav"></div>
<% end %>