config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :projects do
    resources :comments
  end
  resources :posts do
    resources :comments#,  only: [:create, :index, :new]
  end

  resources :comments

  resources "contacts", only: [:new, :create]

  get 'home/index'

  get "text/:text" => Dragonfly.app.endpoint { |params, app|
    app.generate(:text, params[:text], 'font-size' => 42)
  }

  get "image" => Dragonfly.app.endpoint { |params, app|
    app.fetch_file("some/dir/#{params[:file]}").thumb(params[:size])
  }

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Sherman's Portfolio" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p><%= link_to "Home", root_path %> |
  <%= link_to "Work", projects_path %> |
  <%= link_to "Blog", posts_path %> |
  <% if current_user.present? && current_user.editor? %>
    <%= link_to "Admin Comments", comments_path %> |
  <% end %>
  <%= link_to "Contact", new_contact_path %> |
  <% if current_user.present? %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> |
    <%= current_user.email %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path %> |
    <%= link_to "Sign In", new_user_session_path %>
    <%#= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
  <% end %>
  </p>

  <% flash.each do |key, value| %>
    <div class="alert-box round <%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>

</body>
</html>